package br.ufpe.cin.dustdog.objects;

public enum LevelGeneratorObject {
	OBSTACLE_STONE_A,
	OBSTACLE_STONE_B,
	OBSTACLE_STONE_C,
	OBSTACLE_STONE_D,
	OBSTACLE_TREE,
	GARBAGE_PAPER_BALL_A,
	GARBAGE_PAPER_BALL_B,
	GARBAGE_PAPER_BALL_C,
	GARBAGE_COCONUT_STRAW,
	GARBAGE_COCONUT_NO_STRAW,
	GARBAGE_BOTTLE_BROWN,
	GARBAGE_BOTTLE_GREEN,
	GARBAGE_BOTTLE_PURPLE,
	GARBAGE_CAN_GREEN,
	GARBAGE_CAN_RED,
	GARBAGE_CAN_PURPLE,
	GARBAGE_FISHBONE,
	SPECIAL_ITEMS_COOKIE_BOX,
	SPECIAL_ITEMS_CAR_BATTERY,
	SPECIAL_ITEMS_STARFISH,
	NONE
}
